<?php

return [
    'changelog'          => 'Kirby\\Site\\Models\\ChangeLogPage',
    'reference-class'    => 'Kirby\\Site\\Models\\ReferenceClassPage',
    'reference-article'  => 'Kirby\\Site\\Models\\ReferenceArticlePage',
    'reference-section'  => 'Kirby\\Site\\Models\\ReferenceSectionPage',
    'code'               => 'Kirby\\Site\\Models\\CodePage',
    'reference-component' => 'Kirby\\Site\\Models\\ReferenceComponentPage',
    'cookbook'           => 'Kirby\\Site\\Models\\CookbookPage',
    'reference-endpoint'           => 'Kirby\\Site\\Models\\ReferenceEndpointPage',
    'reference-endpoints'          => 'Kirby\\Site\\Models\\ReferenceEndpointsPage',
    'reference-extensions'         => 'Kirby\\Site\\Models\\ReferenceExtensionsPage',
    'reference-fieldmethod'       => 'Kirby\\Site\\Models\\ReferenceFieldMethodPage',
    'reference-fieldmethods'      => 'Kirby\\Site\\Models\\ReferenceFieldMethodsPage',
    'guide'              => 'Kirby\\Site\\Models\\GuidePage',
    'reference-helper'             => 'Kirby\\Site\\Models\\ReferenceHelperPage',
    'reference-hook'               => 'Kirby\\Site\\Models\\ReferenceHookPage',
    'reference-hooks'              => 'Kirby\\Site\\Models\\ReferenceHooksPage',
    'reference-icon'               => 'Kirby\\Site\\Models\\ReferenceIconPage',
    'reference-icons'              => 'Kirby\\Site\\Models\\ReferenceIconsPage',
    'kosmos-issue'       => 'Kirby\\Site\\Models\\KosmosIssuePage',
    'reference-kirbytag'           => 'Kirby\\Site\\Models\\ReferenceKirbyTagPage',
    'reference-classmethod'             => 'Kirby\\Site\\Models\\ReferenceClassMethodPage',
    'reference-packages'           => 'Kirby\\Site\\Models\\ReferencePackagesPage',
    'cookbook-recipe'    => 'Kirby\\Site\\Models\\CookbookRecipePage',
    'reference-root'               => 'Kirby\\Site\\Models\\ReferenceRootPage',
    'reference-roots'              => 'Kirby\\Site\\Models\\ReferenceRootsPage',
    'reference-ui'                 => 'Kirby\\Site\\Models\\ReferenceUiPage',
    'reference-url'                => 'Kirby\\Site\\Models\\ReferenceUrlPage',
    'reference-urls'               => 'Kirby\\Site\\Models\\ReferenceUrlsPage',
    'reference-validator'          => 'Kirby\\Site\\Models\\ReferenceValidatorPage',
    'reference-validators'         => 'Kirby\\Site\\Models\\ReferenceValidatorsPage',
    'voice'              => 'Kirby\\Site\\Models\\VoicePage',
];
