<?php

return [
    'changelog'          => 'Kirby\\Site\\Models\\ChangeLogPage',
    'class'              => 'Kirby\\Site\\Models\\ClassPage',
    'cheatsheet-article' => 'Kirby\\Site\\Models\\CheatsheetArticlePage',
    'cheatsheet-section' => 'Kirby\\Site\\Models\\CheatsheetSectionPage',
    'code'               => 'Kirby\\Site\\Models\\CodePage',
    'component'          => 'Kirby\\Site\\Models\\ComponentPage',
    'cookbook'           => 'Kirby\\Site\\Models\\CookbookPage',
    'endpoint'           => 'Kirby\\Site\\Models\\EndpointPage',
    'endpoints'          => 'Kirby\\Site\\Models\\EndpointsPage',
    'extensions'         => 'Kirby\\Site\\Models\\ExtensionsPage',
    'field-method'       => 'Kirby\\Site\\Models\\FieldMethodPage',
    'field-methods'      => 'Kirby\\Site\\Models\\FieldMethodsPage',
    'guide-chapter'      => 'Kirby\\Site\\Models\\GuideChapterPage',
    'helper'             => 'Kirby\\Site\\Models\\HelperPage',
    'hook'               => 'Kirby\\Site\\Models\\HookPage',
    'hooks'              => 'Kirby\\Site\\Models\\HooksPage',
    'icon'               => 'Kirby\\Site\\Models\\IconPage',
    'icons'              => 'Kirby\\Site\\Models\\IconsPage',
    'kosmos-issue'       => 'Kirby\\Site\\Models\\KosmosIssuePage',
    'kirbytag'           => 'Kirby\\Site\\Models\\KirbyTagPage',
    'method'             => 'Kirby\\Site\\Models\\MethodPage',
    'packages'           => 'Kirby\\Site\\Models\\PackagesPage',
    'cookbook-recipe'    => 'Kirby\\Site\\Models\\CookbookRecipePage',
    'root'               => 'Kirby\\Site\\Models\\RootPage',
    'roots'              => 'Kirby\\Site\\Models\\RootsPage',
    'ui'                 => 'Kirby\\Site\\Models\\UiPage',
    'url'                => 'Kirby\\Site\\Models\\UrlPage',
    'urls'               => 'Kirby\\Site\\Models\\UrlsPage',
    'validator'          => 'Kirby\\Site\\Models\\ValidatorPage',
    'validators'         => 'Kirby\\Site\\Models\\ValidatorsPage',
    'voice'              => 'Kirby\\Site\\Models\\VoicePage',
];
