<?php

return [
    'templatesInclude' => [
        'home',
        'buy',
        'news',
        'community',
        'documentation',
        'guide',
        'coookbook',
        'recipe',
        'reference',
        'reference-kirbytags',
        'reference-kirbytag',
        'reference-section',
        'reference-article',
        'reference-fieldmethods',
        'reference-fieldmethod',
        'reference-classmethod',
        'reference-class',
        'reference-urls',
        'reference-url',
        'reference-roots',
        'reference-root',
        'reference-validators',
        'reference-validator',
        'reference-extensions',
        'reference-extension',
        'reference-hooks',
        'reference-hook',
        'reference-component',
        'reference-endpoints',
        'reference-endpoint',
        'glossary',
        'archive',
        'contact',
        'kosmos',
        'issue',
        'text',
        'cases',
        'plugins',
        'press',
        'search',
        'styleguide',
        'try',
        'release',
        'why',
    ],
    'pagesInclude' => [],
    'pagesExclude' => [
        'docs/reference/@/.*',
    ],
];