<?php

return [
    'templatesInclude' => [
        'home',
        'buy',
        'community',
        'guide',
        'guide.chapter',
        'coookbook',
        'cookbook.recipe',
        'cheatsheet',
        'kirbytags',
        'kirbytag',
        'cheatsheet-section',
        'cheatsheet-article',
        'field-methods',
        'field-method',
        'method',
        'class',
        'urls',
        'url',
        'roots',
        'root',
        'validators',
        'validator',
        'extensions',
        'extension',
        'hooks',
        'hook',
        'component',
        'endpoints',
        'endpoint',
        'glossary',
        'versions',
        'contact',
        'kosmos',
        'kosmos.issue',
        'cases',
        'plugins',
        'press',
        'search',
        'styleguide',
        'try',
        'release',
        'release.35',
        'why',
    ],
    'pagesInclude' => [],
    'pagesExclude' => [
        'docs/reference/@/.*',
    ],
];