<?php

return [
	'1' => [
		'title'       => 'Kirby 1',
		'hasDocs'     => true,
		'mainVersion' => '1',
		'since'       => 'Jan 2012 - Oct 2014',
		'description' => 'has reached its end of life and is no longer supported by us.',
		'link'        => 'https://v11.getkirby.com',
		'repo'        => 'https://github.com/getkirby-v1',
	],
	'2' => [
		'title'       => 'Kirby 2',
		'hasDocs'     => true,
		'mainVersion' => '2',
		'since'       => 'Oct 2014 - Feb 2019',
		'description' => 'has reached its end of life and is no longer supported by us.',
		'link'        => 'https://v25.getkirby.com',
		'repo'        => 'https://github.com/getkirby-v2',
	],
	'3.5' => [
		'title'       => 'Kirby 3.5',
		'hasDocs'     => true,
		'mainVersion' => '3',
		'since'       => 'Dec 2020 - Nov 2021',
		'description' => 'has reached its end of life and is no longer supported by us.',
		'link'        => 'https://v35.getkirby.com/docs',
		'repo'        => 'https://github.com/getkirby',
	],
	'3.6' => [
		'title'       => 'Kirby 3.6',
		'hasDocs'     => true,
		'mainVersion' => '3',
		'since'       => 'Nov 2021 - June 2022',
		'description' => 'has reached its end of life and is no longer supported by us.',
		'link'        => 'https://v36.getkirby.com/docs',
		'repo'        => 'https://github.com/getkirby',
	],
	'3.7' => [
		'title'       => 'Kirby 3.7',
		'hasDocs'     => true,
		'mainVersion' => '3',
		'since'       => 'June 2022 - Oct 2022',
		'description' => 'has reached its end of life and is no longer supported by us.',
		'link'        => 'https://v37.getkirby.com/docs',
		'repo'        => 'https://github.com/getkirby',
	],
	'3.8' => [
		'title'       => 'Kirby 3.8',
		'hasDocs'     => true,
		'mainVersion' => '3',
		'since'       => 'Oct 2022 - Jan 2023',
		'description' => 'is not the most current version of Kirby and should not be used for new projects.',
		'link'        => 'https://v38.getkirby.com/docs',
		'repo'        => 'https://github.com/getkirby',
	],
	'3.9' => [
		'title'       => 'Kirby 3.9',
		'hasDocs'     => true,
		'mainVersion' => '3',
		'since'       => 'Jan 2023 - Nov 2023',
		'description' => 'is not the most current version of Kirby and should not be used for new projects.',
		'link'        => 'https://v39.getkirby.com/docs',
		'repo'        => 'https://github.com/getkirby',
	],
	'3.10' => [
		'title'       => 'Kirby 3.10',
		'hasDocs'     => true,
		'mainVersion' => '3',
		'since'       => 'Nov 2023',
		'description' => 'is not the most current version of Kirby and should not be used for new projects.',
		'link'        => 'https://v39.getkirby.com/docs',
		'repo'        => 'https://github.com/getkirby',
	],
	'4' => [
		'title'       => 'Kirby 4.0',
		'hasDocs'     => true,
		'mainVersion' => '4',
		'since'       => 'Nov 2023 - June 2025',
		'description' => 'is not the most current version of Kirby and should not be used for new projects.',
		'link'        => 'https://v4.getkirby.com/docs',
		'repo'        => 'https://github.com/getkirby',
	],
	'5' => [
		'title'       => 'Kirby 5.0',
		'hasDocs'     => true,
		'mainVersion' => '5',
		'since'       => 'June 2025',
		'description' => 'is the latest version of Kirby. <br><strong class="color-black">Start new projects with this version!</strong>',
		'link'        => 'https://getkirby.com/docs',
		'repo'        => 'https://github.com/getkirby',
	],
];
