#!/usr/bin/env php
<?php

define('ROOT', dirname(__DIR__));

define('DEFAULT_CONFIG', ROOT . '/config.default.json');
define('USER_CONFIG', ROOT . '/config.json');
define('BACKSTOP_DEFAULTS', ROOT . '/backstop.default.json');
define('BACKSTOP_CONFIG', ROOT . '/backstop.json');

$config = json_decode(file_get_contents(DEFAULT_CONFIG), true);
if (file_exists(USER_CONFIG)) {
  $config = array_merge($config, json_decode(file_get_contents(USER_CONFIG), true));
}

$scenarios = @file_get_contents("http://{$config['host']}/backstop-scenarios");

if ($scenarios === false) {
  echo "Could not generate the sitemap for backstop. It seems, that the test server is not running properly at {$config['host']}.";
  exit(1);
}

$scenarios = json_decode($scenarios, true);

$backstopDefaults = json_decode(file_get_contents(BACKSTOP_DEFAULTS), true);
$backstopConfig = array_merge($backstopDefaults, $scenarios);

file_put_contents(BACKSTOP_CONFIG, json_encode($backstopConfig, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
