#!/usr/bin/env php
<?php

/**
 * CLI script to re-index the Kirby Loupe index
 *
 * @author Lukas Bestle <lukas@getkirby.com>
 * @author Ahmet Bora <ahmet@getkirby.com>
 */

use Kirby\Cms\App;
use Kirby\Search\LoupeSearch;

// check if we are indeed on the command line
if (php_sapi_name() !== 'cli') {
  die();
}
ini_set('memory_limit', '2048M');
define('KIRBY_HELPER_VIDEO', false);

// load Kirby
require __DIR__ . '/../kirby/bootstrap.php';

$props = [
  'roots' => [
      'index'   => __DIR__ . '/..',
      'content' => __DIR__ . '/../content',
      'site'    => __DIR__ . '/../site',
  ],
];

// initialize Kirby and site
echo "\033[1mLoading Kirby...\033[0m\n";
$kirby = new App($props);

// re-index using the Search plugin
echo "\033[1mReindexing using the Loupe search plugin...\033[0m\n";
$search = LoupeSearch::instance();
$search->index()->generate();

echo "\033[32mSuccessfully indexed the Kirby site.\033[0m\n";