name: Compile assets

on:
  push:
    paths:
      - 'www/assets/**'
  pull_request:
    paths:
      - 'www/assets/**'

jobs:
  assets:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Compiled assets dist files
          file_pattern: www/dist/*
