name: Compile dist

on:
  pull_request_review:
    types:
      - submitted

jobs:
  build:
    if: github.event.review.state == 'approved'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout getkirby.com
        uses: actions/checkout@v2

      - name: Setup Node environment
        uses: actions/setup-node@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: npm ci

      - name: Build dist for assets
        run: npm run build

      - name: Commit dist files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dist files for assets
          file_pattern: www/dist/*
