
name: SVG optimization

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: ericcornelissen/svgo-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        comment: true
